# Generated by Django 5.2.6 on 2025-10-25 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_chat_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 13, 0, 4, 2259, tzinfo=datetime.timezone.utc)),
        ),
    ]
