# Generated by Django 5.2.7 on 2025-10-29 04:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
