# Generated by Django 5.2.6 on 2025-10-25 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 25, 14, 22, 58, 306371, tzinfo=datetime.timezone.utc)),
        ),
    ]
