# Generated by Django 5.2.6 on 2025-10-26 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 26, 0, 54, 34, 251112, tzinfo=datetime.timezone.utc)),
        ),
    ]
