# Generated by Django 5.2.7 on 2025-10-27 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_message_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 14, 55, 49, 87557, tzinfo=datetime.timezone.utc)),
        ),
    ]
