# Generated by Django 5.2.7 on 2025-10-27 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_message_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 27, 16, 19, 4, 452750, tzinfo=datetime.timezone.utc)),
        ),
    ]
