# Generated by Django 5.2.6 on 2025-10-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
