# Generated by Django 5.2.6 on 2025-10-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_comment_videocomment_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='posted_on',
            new_name='created_on',
        ),
    ]
