# Generated by Django 5.2.6 on 2025-10-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_posted_on_video_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.CharField(default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='videocomment',
            name='type',
            field=models.CharField(default='comment', max_length=20),
        ),
    ]
