# Generated by Django 5.2.6 on 2025-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_post_type_video_type_videocomment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='type',
            field=models.CharField(default='comment', max_length=20),
        ),
    ]
