# Generated by Django 5.2.6 on 2025-10-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_postcomment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='type',
            field=models.CharField(default='postComment', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='type',
            field=models.CharField(default='videoComment', max_length=20),
        ),
    ]
