# Generated by Django 5.2.6 on 2025-10-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_postcomment_type_alter_videocomment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='postImages/'),
        ),
    ]
