# Generated by Django 5.2.6 on 2025-10-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('DOCS', 'Documentation'), ('NEW', 'Enhancement'), ('HUH?', 'Question')], max_length=50)),
            ],
        ),
    ]
