# Generated by Django 5.2.6 on 2025-10-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='type',
            field=models.CharField(choices=[('BUG', 'Bug'), ('DOCS', 'Documentation'), ('NEW', 'Enhancement'), ('HUH?', 'Question')], default='BUG', max_length=50),
        ),
    ]
