# Generated by Django 5.2.6 on 2025-10-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_bugreport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='github_issue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
