# Generated by Django 5.2.6 on 2025-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_post_image_bugreport_github_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='github_issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
