# Generated by Django 5.2.6 on 2025-10-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_bugreport_github_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='has_github_issue',
            field=models.BooleanField(default=False),
        ),
    ]
