# Generated by Django 5.2.7 on 2026-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
