# Generated by Django 5.2.7 on 2026-02-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_bugreport_resolved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugReport',
        ),
    ]
