# Generated by Django 5.2.7 on 2026-02-15 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_bugreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='postImages/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'webp', 'heif', 'jpg'])]),
        ),
    ]
