# Generated by Django 5.2.7 on 2026-02-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_post_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
