# Generated by Django 5.2.7 on 2026-02-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
