# Generated by Django 5.2.7 on 2026-02-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_post_author_alter_video_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocomment',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
