# Generated by Django 5.2.7 on 2026-02-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_postcomment_author_alter_videocomment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
