# Generated by Django 5.2.7 on 2026-03-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='expires_on',
            field=models.DateTimeField(null=True),
        ),
    ]
