# Generated by Django 5.2.7 on 2026-04-07 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_banner_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_size',
            field=models.IntegerField(default=19, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
