# Generated by Django 5.2.7 on 2026-02-11 20:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and +/-/_ only.', max_length=150, unique=True, validators=[accounts.models.CustomUsernameValidator()]),
        ),
    ]
