# Generated by Django 5.2.7 on 2026-04-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='use_naughty_words',
            field=models.BooleanField(default=False),
        ),
    ]
