# Generated by Django 5.2.7 on 2026-05-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_use_naughty_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='static/img/pfpDefault.png', upload_to='profilePics'),
        ),
    ]
