# Generated by Django 5.2.7 on 2026-05-28 16:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_use_naughty_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Profile Description'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/pfpDefault.png', upload_to='profilePics', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and +/-/_ only.', max_length=32, unique=True, validators=[accounts.models.CustomUsernameValidator()]),
        ),
    ]
