# Generated by Django 5.2.7 on 2026-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(null=True, verbose_name='Profile Description'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='static/img/pfpDefault.png', upload_to='profilePics', verbose_name='Profile Picture'),
        ),
    ]
