# Generated by Django 5.2.7 on 2026-05-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Profile Description'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/img/pfpDefault.png', upload_to='profilePics', verbose_name='Profile Picture'),
        ),
    ]
