# Generated by Django 5.2.7 on 2026-05-28 16:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and +/-/_ only.', max_length=32, unique=True, validators=[accounts.models.CustomUsernameValidator()]),
        ),
    ]
