# Generated by Django 5.2.7 on 2026-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='use_naughty_words',
            field=models.BooleanField(default=False, verbose_name='Filters'),
        ),
    ]
