# Generated by Django 5.2.7 on 2026-05-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_use_naughty_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='use_naughty_words',
            field=models.BooleanField(default=False, null=True, verbose_name='Filters'),
        ),
    ]
