# Generated by Django 5.2.7 on 2026-05-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_use_naughty_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='use_naughty_words',
            field=models.BooleanField(blank=True, default=False, verbose_name='Filters\\'),
        ),
    ]
