# Generated by Django 5.2.7 on 2026-05-28 16:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_use_naughty_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='use_naughty_words',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Filters'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required. 32 characters or fewer. Letters, digits and +/-/_ only.', max_length=32, unique=True, validators=[accounts.models.CustomUsernameValidator()]),
        ),
    ]
