# Generated by Django 5.2.7 on 2026-05-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_use_naughty_words_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='use_naughty_words',
            field=models.BooleanField(blank=True, choices=[(True, 'Off'), (False, 'On')], default=False, verbose_name='Filters'),
        ),
    ]
