# Generated by Django 5.2.7 on 2026-02-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='admin', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('DOCS', 'Documentation'), ('NEW', 'Enhancement'), ('HUH?', 'Question')], default='BUG', max_length=50)),
                ('github_issue', models.CharField(blank=True, max_length=100, null=True)),
                ('has_github_issue', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
