# Generated by Django 5.2.7 on 2026-05-01 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreport',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='issues',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='SubBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bugs.bugreport')),
            ],
        ),
    ]
