# Generated by Django 5.2.7 on 2026-05-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_rename_body_bugreport_description_bugreport_issues_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubBug',
            new_name='BugIssues',
        ),
    ]
