# Generated by Django 5.2.7 on 2026-05-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_rename_subbug_bugissues'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='issueModel',
            field=models.ManyToManyField(to='bugs.bugissues'),
        ),
    ]
