# Generated by Django 5.2.7 on 2026-05-04 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0004_bugreport_issuemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugissues',
            old_name='completed',
            new_name='resolved',
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='issueModel',
            field=models.ManyToManyField(blank=True, null=True, to='bugs.bugissues'),
        ),
    ]
