# Generated by Django 5.2.7 on 2026-05-04 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0005_rename_completed_bugissues_resolved_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BugIssues',
            new_name='BugIssue',
        ),
    ]
