# Generated by Django 5.2.7 on 2026-05-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0006_rename_bugissues_bugissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugissue',
            name='issue',
            field=models.CharField(max_length=255),
        ),
    ]
