# Generated by Django 5.2.7 on 2026-05-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0008_alter_bugissue_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='issueModel',
            field=models.ManyToManyField(blank=True, to='bugs.bugissue'),
        ),
    ]
