# Generated by Django 5.2.7 on 2026-03-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/')),
                ('downloads', models.IntegerField()),
            ],
        ),
    ]
