# Generated by Django 5.2.7 on 2026-03-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
