# Generated by Django 5.2.7 on 2026-03-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_upload_file_name_alter_upload_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.CharField(default='receipts', max_length=50),
            preserve_default=False,
        ),
    ]
