# Generated by Django 5.2.7 on 2026-03-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_alter_upload_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
